### ISSUE TITLE
docker-maven-plugin

### ISSUE THREAD

**Issue by alexec** [etux/docker-maven-plugin#4]
Hi there,

I see I'm not the only person out there with this idea:

https://github.com/rhuss/docker-maven-plugin
https://github.com/bibryam/docker-maven-plugin
https://github.com/etux/docker-maven-plugin
https://github.com/alexec/docker-maven-plugin

What's your thoughts on some kind of collaboration?

Alex

**Comment by etux** [comment]
I would love to collaborate with others.  Feel free to fork my repo or recommend a better one so I can push my code to it. I'm willing to rename it so that is not such a personal project
